name: Unit Tests

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check-sql-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PyGithub
          pip install sqlparse

      - name: Unit Tests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python .github/scripts/unit_tests.py

      - name: Comment on PR
        uses: actions/github-script@v5
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const { owner, repo, number } = context.issue;
            const message = process.env.REVIEW_MESSAGE;
            const result = await github.rest.issues.createComment({
              owner,
              repo,
              issue_number: number,
              body: message,
            });
