name: Unit Tests

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check-sql-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PyGithub
          pip install sqlparse

      - name: Teste SQL
        run: python .github/scripts/sql_unit_tests.py

      - name: Reacoes
        run: python .github/scripts/teste_reacoes_pr.py
